//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SchoolOO.DAO
{
    public partial class OfficeAssignment
    {
        #region Primitive Properties
    
        public virtual int InstructorID
        {
            get { return _instructorID; }
            set
            {
                if (_instructorID != value)
                {
                    if (Person != null && Person.PersonID != value)
                    {
                        Person = null;
                    }
                    _instructorID = value;
                }
            }
        }
        private int _instructorID;
    
        public virtual string Location
        {
            get;
            set;
        }
    
        public virtual byte[] Timestamp
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Person Person
        {
            get { return _person; }
            set
            {
                if (!ReferenceEquals(_person, value))
                {
                    var previousValue = _person;
                    _person = value;
                    FixupPerson(previousValue);
                }
            }
        }
        private Person _person;

        #endregion
        #region Association Fixup
    
        private void FixupPerson(Person previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.OfficeAssignment, this))
            {
                previousValue.OfficeAssignment = null;
            }
    
            if (Person != null)
            {
                Person.OfficeAssignment = this;
                if (InstructorID != Person.PersonID)
                {
                    InstructorID = Person.PersonID;
                }
            }
        }

        #endregion
    }
}
