//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SchoolOO.DAO
{
    public partial class OnsiteCourse
    {
        #region Primitive Properties
    
        public virtual int CourseID
        {
            get { return _courseID; }
            set
            {
                if (_courseID != value)
                {
                    if (Course != null && Course.CourseID != value)
                    {
                        Course = null;
                    }
                    _courseID = value;
                }
            }
        }
        private int _courseID;
    
        public virtual string Location
        {
            get;
            set;
        }
    
        public virtual string Days
        {
            get;
            set;
        }
    
        public virtual System.DateTime Time
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Course Course
        {
            get { return _course; }
            set
            {
                if (!ReferenceEquals(_course, value))
                {
                    var previousValue = _course;
                    _course = value;
                    FixupCourse(previousValue);
                }
            }
        }
        private Course _course;

        #endregion
        #region Association Fixup
    
        private void FixupCourse(Course previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.OnsiteCourse, this))
            {
                previousValue.OnsiteCourse = null;
            }
    
            if (Course != null)
            {
                Course.OnsiteCourse = this;
                if (CourseID != Course.CourseID)
                {
                    CourseID = Course.CourseID;
                }
            }
        }

        #endregion
    }
}
