//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace SchoolOO.DAO
{
    public partial class SchoolEntities : ObjectContext
    {
        public const string ConnectionString = "name=SchoolEntities";
        public const string ContainerName = "SchoolEntities";
    
        #region Constructors
    
        public SchoolEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public SchoolEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public SchoolEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Course> Courses
        {
            get { return _courses  ?? (_courses = CreateObjectSet<Course>("Courses")); }
        }
        private ObjectSet<Course> _courses;
    
        public ObjectSet<Department> Departments
        {
            get { return _departments  ?? (_departments = CreateObjectSet<Department>("Departments")); }
        }
        private ObjectSet<Department> _departments;
    
        public ObjectSet<OfficeAssignment> OfficeAssignments
        {
            get { return _officeAssignments  ?? (_officeAssignments = CreateObjectSet<OfficeAssignment>("OfficeAssignments")); }
        }
        private ObjectSet<OfficeAssignment> _officeAssignments;
    
        public ObjectSet<OnlineCourse> OnlineCourses
        {
            get { return _onlineCourses  ?? (_onlineCourses = CreateObjectSet<OnlineCourse>("OnlineCourses")); }
        }
        private ObjectSet<OnlineCourse> _onlineCourses;
    
        public ObjectSet<OnsiteCourse> OnsiteCourses
        {
            get { return _onsiteCourses  ?? (_onsiteCourses = CreateObjectSet<OnsiteCourse>("OnsiteCourses")); }
        }
        private ObjectSet<OnsiteCourse> _onsiteCourses;
    
        public ObjectSet<Person> People
        {
            get { return _people  ?? (_people = CreateObjectSet<Person>("People")); }
        }
        private ObjectSet<Person> _people;
    
        public ObjectSet<StudentGrade> StudentGrades
        {
            get { return _studentGrades  ?? (_studentGrades = CreateObjectSet<StudentGrade>("StudentGrades")); }
        }
        private ObjectSet<StudentGrade> _studentGrades;

        #endregion
    }
}
