//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SchoolOO.DAO
{
    public partial class StudentGrade
    {
        #region Primitive Properties
    
        public virtual int EnrollmentID
        {
            get;
            set;
        }
    
        public virtual int CourseID
        {
            get { return _courseID; }
            set
            {
                if (_courseID != value)
                {
                    if (Course != null && Course.CourseID != value)
                    {
                        Course = null;
                    }
                    _courseID = value;
                }
            }
        }
        private int _courseID;
    
        public virtual int StudentID
        {
            get { return _studentID; }
            set
            {
                if (_studentID != value)
                {
                    if (Person != null && Person.PersonID != value)
                    {
                        Person = null;
                    }
                    _studentID = value;
                }
            }
        }
        private int _studentID;
    
        public virtual Nullable<decimal> Grade
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Course Course
        {
            get { return _course; }
            set
            {
                if (!ReferenceEquals(_course, value))
                {
                    var previousValue = _course;
                    _course = value;
                    FixupCourse(previousValue);
                }
            }
        }
        private Course _course;
    
        public virtual Person Person
        {
            get { return _person; }
            set
            {
                if (!ReferenceEquals(_person, value))
                {
                    var previousValue = _person;
                    _person = value;
                    FixupPerson(previousValue);
                }
            }
        }
        private Person _person;

        #endregion
        #region Association Fixup
    
        private void FixupCourse(Course previousValue)
        {
            if (previousValue != null && previousValue.StudentGrades.Contains(this))
            {
                previousValue.StudentGrades.Remove(this);
            }
    
            if (Course != null)
            {
                if (!Course.StudentGrades.Contains(this))
                {
                    Course.StudentGrades.Add(this);
                }
                if (CourseID != Course.CourseID)
                {
                    CourseID = Course.CourseID;
                }
            }
        }
    
        private void FixupPerson(Person previousValue)
        {
            if (previousValue != null && previousValue.StudentGrades.Contains(this))
            {
                previousValue.StudentGrades.Remove(this);
            }
    
            if (Person != null)
            {
                if (!Person.StudentGrades.Contains(this))
                {
                    Person.StudentGrades.Add(this);
                }
                if (StudentID != Person.PersonID)
                {
                    StudentID = Person.PersonID;
                }
            }
        }

        #endregion
    }
}
